openapi: 3.0.0
servers:
  - url: 'https://phantomsxr.com/api/v2/client'
    description: ''
    variables: {}
info:
  version: v2
  title: XRMOD Cloud v2 Collection
  description: Use the xrmod cloud api for xr content that you own and that creators share.
  termsOfService: ''
  contact: {}
  license:
    name: ''
paths:
  /getarprojectlist:
   get:
      summary: Get all projects
      description: |
        Get a list of XR experience created by an vaild license.
      operationId: GetARProjectList
      parameters: 
        - $ref: '#/components/parameters/app_package_id'
        - $ref: '#/components/parameters/page_size'
        - $ref: '#/components/parameters/page_num'
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/securitySchemes'
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    code: 200,
                    message: ''
                    data:                      
                      all_project:
                        - app_uid: 3663670167 
                          user_uid: 1012451543
                          project_uid: 3749040281
                          project_name: "SLAMSample"
                          project_brief: "Place an virutal object in real world."
                          project_icon: "https://../AR_icon.jpg"
                          create_time: "2022-11-11T04:01:18.429109Z"
                          update_time: "2022-11-11T04:01:18.429109Z"
                          project_type: 0
      tags:
        - Get XR-Experience
  
  /getrecommandlist:
    get:
      summary: Get recommand projects
      description: |
        Get a list of XR-erxperience flagged as recommended.
      operationId: GetRecommendList
      parameters: 
        - $ref: '#/components/securitySchemes'
        - $ref: '#/components/parameters/platform'

      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    code: 200,
                    message: ''
                    data:                      
                      all_project:
                        - app_uid: 3663670167 
                          user_uid: 1012451543
                          project_uid: 3749040281
                          project_name: "SLAMSample"
                          project_brief: "Place an virutal object in real world."
                          project_icon: "https://../AR_icon.jpg"
                          create_time: "2022-11-11T04:01:18.429109Z"
                          update_time: "2022-11-11T04:01:18.429109Z"
                          project_type: 0
      tags:
        - Get XR-Experience
 
  /getarprojectdetail:
    get:
      summary: Get project detail
      description: |
        Via project uid to get a XR-Experience project deatil.
      operationId: GetARProjectDetail
      parameters: 
        - $ref: '#/components/parameters/project_uid'
        - $ref: '#/components/parameters/app_package_id'
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/securitySchemes'
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    code: 200,
                    message: ''
                    data:
                      app_uid: 3663670167,
                      user_uid: 1012451543,
                      project_uid: 2917042829,
                      project_name: "Solar System AR"
                      project_brief: "project_brief"
                      project_description: "Descript for solar system."
                      project_icon: 
                        "https://.../1012451543/3663670167/2917042829.jpg"
                      project_header: 
                        "https://.../1012451543/3663670167/2917042829.jpg"
                      project_preview: 
                        "{\"project_preview_0\": \"https://...\falloutcar.png?t=1667834781685\"}",
                      create_time: "2022-11-07T15:26:21.691628Z",
                      update_time: "2022-11-11T04:20:29.633652Z",
      tags:
        - Get XR-Experience
      
  /getarresources:
    get:
      summary: Get ar resources
      description: |
        Via project uid to get a XR-Experience resources.
      operationId: GetARProjectResources
      parameters: 
        - $ref: '#/components/parameters/project_uid'
        - $ref: '#/components/parameters/platform'
        - $ref: '#/components/securitySchemes'
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    code: 200,
                    message: ''
                    data:
                      app_uid: 3663670167,
                      user_uid: 1012451543,
                      project_uid: 2917042829,
                      bundle_size: 0.2
                      json_url: "https://.../1012451543/3663670167/2917042829.json"
                      bundle_url: "https://.../1012451543/3663670167/2917042829.arexperience"
                      platform_type: "iOS"
                      create_time: "2022-11-07T15:26:21.691628Z",
                      update_time: "2022-11-11T04:20:29.633652Z",
      tags:
        - Get XR-Experience
  
  /getudmproject :
    get:
      summary: Get udm project
      description: |
        Get the configuration information of the UDM project
      operationId: GetUDMProject
      parameters: 
        - $ref: '#/components/parameters/user_uid'
        - $ref: '#/components/parameters/app_uid'
        - $ref: '#/components/parameters/project_uid'
        - $ref: '#/components/parameters/data_type'
        - $ref: '#/components/parameters/part_category'
        - $ref: '#/components/parameters/part_type'
        - $ref: '#/components/securitySchemes'
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    code: 200,
                    message: ''
                    data:
                      id: 48
                      app_uid: 3663670167,
                      user_uid: 1012451543,
                      project_uid: 2917042829,
                      project_data:
                          hotspot_list: []
                          main_project:
                            transform:
                              scale:
                                x: 0.1
                                y: 0.1
                                z: 0.1
                              position:
                                x: 0
                                y: 0
                                z: 0
                              rotation:
                                x: 0
                                y: 0
                                z: 0
                            object_url: "https://...url"
                      tooltip_list: []
                      component_list: 
                        - attach_node:  "cf54e5b166644fc7ade7bbaac502a04f"
                          component_data:  "{\"center\":{\"x\":2.7725143432617189,\"y\":42.99409484863281,\"z\":-255.87876892089845},\"extents\":{\"x\":327.34979248046877,\"y\":159.8909912109375,\"z\":-599.4797973632813},\"min\":{\"x\":0.0,\"y\":0.0,\"z\":0.0},\"max\":{\"x\":0.0,\"y\":0.0,\"z\":0.0}}"
                          component_type: "BoundComponent"
                      object_partproperty_list: []
      tags:
        - Get UDM
  
  /getudmparts:
    get:
      summary: Get udm parts
      description: |
        Get the configuration information of the UDM project
      operationId: GetUDMParts
      parameters: 
        - $ref: '#/components/parameters/user_uid'
        - $ref: '#/components/parameters/app_uid'
        - $ref: '#/components/parameters/project_uid'
        - $ref: '#/components/parameters/data_type'
        - $ref: '#/components/parameters/part_category'
        - $ref: '#/components/parameters/part_type'
        - $ref: '#/components/securitySchemes'
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    code: 200,
                    message: ''
                    data:
                      id: 48
                      app_uid: 3663670167,
                      user_uid: 1012451543,
                      project_uid: 2917042829,
                      part_type: "3DModel"
                      part_category: "XXXX"
                      part_item_count: 2
                      parts:
                        - part_name: "Fish"
                          part_type_id: 143
                          part_sku: "1002"
                          part_thumbnail_url: "https://....xxx"
                          transform:
                              scale:
                                x: 0.1
                                y: 0.1
                                z: 0.1
                              position:
                                x: 0
                                y: 0
                                z: 0
                              rotation:
                                x: 0
                                y: 0
                                z: 0
      tags:
        - Get UDM
  
components:
  parameters:
    app_package_id:
      name: app_package_id
      in: query
      required: true
      schema:
        type: string
    page_size:
      name: page_size
      in: query
      required: true
      schema:
        type: number
    page_num:
      name: page_num
      in: query
      required: true
      schema:
        type: number
    project_uid:
      name: project_uid
      in: query
      required: true
      schema:
        type: string
    platform:
      name: platform
      in: query
      required: true
      schema:
        type: string
    data_type:
      name: data_type
      in: query
      required: true
      schema:
        type: string
      description: list or mainproject
    part_category:
      name: part_category
      in: query
      required: true
      schema:
        type: string
    part_type:
      name: part_type
      in: query
      required: true
      schema:
        type: string
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
      description: |-
        Prefix the value with `Token` to indicate the custom authorization type
      
tags:
  - name: Get XR-Experience
  - name: Get UDM
externalDocs:
  url: ''
  description: ''
security:
  - Authorization: []
